//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MikuMikuGameEngine.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MikuMikuGameEngTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_ASSETEXPLORER               155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_OBJECT_LIST_VIEW            159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDI_OBJECTLIST_VIEW             169
#define IDB_EXPLORER_24                 170
#define IDI_OBJECTLIST_VIEW_HC          170
#define IDR_SORT                        171
#define IDI_ASSETEXPLORER               171
#define IDB_SORT_24                     172
#define IDI_ASSETEXPLORER_HC            172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_VIEW_OBJECTLISTVIEW          310
#define IDR_POPUP_OBJECTLIST            310
#define ID_VIEW_ASSETEXPLORER           311
#define IDB_TOON01                      314
#define IDB_TOON02                      316
#define IDB_TOON03                      317
#define IDB_TOON04                      318
#define IDB_TOON05                      319
#define IDB_TOON06                      320
#define IDB_TOON07                      321
#define IDB_TOON08                      322
#define IDB_TOON09                      323
#define IDB_TOON10                      324
#define IDR_TEXTURE_CONTROL_UI          327
#define IDR_RCDATA1                     329
#define IDR_ATLAS_CONTROL_UI            329
#define IDR_RCDATA2                     330
#define IDR_MODEL_AXIS                  330
#define ID_POPUP_32771                  32771
#define ID_POPUP_32772                  32772
#define ID_ADD_OBJECT                   32773
#define ID_DELETE_OBJECT                32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_ADD_FOLDER                   32778
#define ID_OPEN_ASSET                   32779
#define ID_32780                        32780
#define ID_32781                        32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
